"""Add files table

Revision ID: f3278e38c273
Revises: 0002_message_generation_metadata
Create Date: 2026-09-04 00:04:09.103855
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f3278e38c273'
down_revision: str | None = '0002_message_generation_metadata'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_created_at'), 'files', ['created_at'], unique=False)
    op.create_index('ix_files_project_created_at', 'files', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_index(op.f('ix_files_storage_key'), 'files', ['storage_key'], unique=True)
    op.create_index('ix_files_user_created_at', 'files', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_files_user_id'), 'files', ['user_id'], unique=False)
    op.drop_index('ix_messages_provider_created_at', table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_provider_created_at', 'messages', ['provider', 'created_at'], unique=False)
    op.drop_index(op.f('ix_files_user_id'), table_name='files')
    op.drop_index('ix_files_user_created_at', table_name='files')
    op.drop_index(op.f('ix_files_storage_key'), table_name='files')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_index('ix_files_project_created_at', table_name='files')
    op.drop_index(op.f('ix_files_created_at'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
